export const POST_ACTIONS = {
  FETCH_POSTS_REQUEST: "FETCH_POSTS_REQUEST",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
  FETCH_COMMENTS_REQUEST: "FETCH_COMMENTS_REQUEST",
  FETCH_COMMENTS_SUCCESS: "FETCH_COMMENTS_SUCCESS",
  FETCH_COMMENTS_FAILURE: "FETCH_COMMENTS_FAILURE",
  FETCH_USERS_POST_REQUEST: "FETCH_USERS_POST_REQUEST",
  FETCH_USERS_POST_SUCCESS: "FETCH_USERS_POST_SUCCESS",
  FETCH_USERS_POST_FAILURE: "FETCH_USERS_POST_FAILURE",
  FETCH_TAGS_POST_REQUEST: "FETCH_TAGS_POST_REQUEST",
  FETCH_TAGS_POST_SUCCESS: "FETCH_TAGS_POST_SUCCESS",
  FETCH_TAGS_POST_FAILURE: "FETCH_TAGS_POST_FAILURE",
};
